language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t lawrencelkp/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true lawrencelkp/docker-react npm run test
